### ISSUE TITLE
Kubernetes 1.16 Support

### ISSUE THREAD

**Issue by Lamby123** [zeebe-io/zeebe-helm#8] opened 2019-12-10 16:13 UTC
I have attempted to deploy Zeebe Full onto Rancher (v2.2.X) running version 1.16.3 of kubernetes. 
The deployment instantly fails with the following error message:

Failed to install app zeebe-full. Error: validation failed: unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1"

Do you have any ideas on where to progress from here?

**Comment by salaboy** [comment] 2019-12-10 16:16
@Lamby123 there seems to be some issues with 1.16 based on the GKV of some of the kubernetes resources. There is another issue about that.. I would rename this issue to kubernetes 1.16 instead of rancher.. I am sure that Rancher has nothing to do with the problem.

**Comment by salaboy** [comment] 2019-12-10 16:17
@Lamby123 I am closing this issue as this is a duplicate of: https://github.com/zeebe-io/zeebe-helm/issues/6

**Closed as completed** 2019-12-10 16:17 UTC
Labels: duplicate
